apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aks-7280"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aks-7280"
  template:
    metadata:
      labels:
        app: "aks-7280"
    spec:
      containers:
        - name: "aks-7280"
          image: "aksa1.azurecr.io/aks"
          ports:
          - containerPort: 80